# Solarized Based Theme
include kitty-themes/tokyonight_moon.conf

# Performance Settings
include lib/performance.conf

# Terminal Bell Settings
include lib/terminal-bell.conf

# Tab Bar Layout
include lib/tabBar-layout.conf

# Advance Options for kitty
include lib/advance-options.conf

# Keyboard config
include lib/keymaps.conf

include lib/mouse-url.conf

# Setting my custom font_family
font_family      JetBrainsMono NF
bold_font        auto
italic_font      auto
bold_italic_font auto

# Setting Font Size
font_size 13

# Background Settings
background_opacity    0.8
dynamic_background_opacity no

# Undercurl
undercurl_style thick-sparse

# kitty controls how to composites text glyphs onto the background color
text_composition_strategy platform

# Scrollback Settings
wheel_scroll_multiplier 5.0
wheel_scroll_min_lines 1

# Hide window decoration
hide_window_decorations no

# window padding width
window_padding_width 2

# window margin width
window_margin_width 2
