##########
# Fonts #
#########
font_size 13
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
undercurl_style thick-sparse

##########
# Cursor #
##########
cursor_shape block
cursor_shape_unfocused hollow
cursor_blink_interval -1

#########
# Mouse #
#########
url_color #fca7ea
open_url_with default
detect_urls yes
underline_hyperlinks hover

###############
# Performance #
###############
repaint_daily 10
input_delay 3
sync_to_monitor yes

###########
# Tab Bar #
###########
tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_align left
tab_switch_strategy previous
tab_title_max_length 20
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title}"

#################
# Window Border #
################
window_margin_width 2
window_padding_width 1
placement_strategy center

###############
# ColorScheme #
###############
include tokyonight_moon.conf
dynamic_background_opacity yes

###################
# Advance Options #
###################
shell .
editor nvim
close_on_child_death no
allow_remote_control no
clipboard_control write-clipboard write-primary read-clipboard-ask read-primary-ask
clipboard_max_size 1024
allow_hyprlinks yes
shell_integration enabled
