format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

right_format = """
$shell\
$time\
"""

[shell]
disabled = false

[time]
use_12hr = true
disabled = false
time_format = "%I:%M %p"
