# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# # A minimal left prompt
# format = """$shell$character"""

right_format = """$time"""

[character]
success_symbol = '[❯](bold green)'

[package]
disabled = false

# Shell Configuration
[shell]
fish_indicator = "fish"
pwsh_indicator = "pwsh"
bash_indicator = "bash"
disabled = false

[time]
disabled = false
use_12hr = true

[username]
style_user = 'white bold'
style_root = 'red bold'
format = 'user: [$user]($style) '
disabled = false
show_always = true
